### PR TITLE
Add error type string formatting tests

### PR DESCRIPTION
**Pull request by waltdisgrace**
Addresses #384.
Supersedes #409.

### CODE REVIEW

**Comment by bgurney-rh** [comment]
These are run as part of "unittest-tests", which isn't executed in the ci script yet.

**Comment by waltdisgrace** [comment]
Rebased.

**Comment by jbaublitz** [comment]
@waltdisgrace Please rebase again.

**Comment by waltdisgrace** [comment]
Rebased.

**Pull request merged**
