### PR TITLE
Add dependencies on auto-generation libraries

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #40.

### CODE REVIEW

**Comment by mulkieran** [comment]
Some extremely rough checks to determine if this approach is more computationally expensive:

```
New style:
  import 0.5729825559537858
  import 0.5634478928986937
  import 0.5688754610018805

Old style:
  import 0.5764175129588693
  import 0.5637675239704549

stratis_cli:

Old style:
  D-Bus Tests:
    real    0m33.383s
    user    0m1.144s
    sys     0m0.274s

New style:
  D-Bus Tests:
    real    0m33.259s
    user    0m1.069s
    sys     0m0.251s
```

The answer seems to be no.

**Comment by mulkieran** [comment]
@agrover review?

**Comment by agrover** [comment]
👍

**Comment by mulkieran** [comment]
Squashed two commits that belong together into "Copy simple connection..."

**Comment by mulkieran** [comment]
Another squash to make "Add dependencies ..." commit more coherent.

**Comment by mulkieran** [comment]
Whoops! There is a bug. it is probably unwise to get the managed objects twice in a single method.

**Comment by mulkieran** [comment]
Wierd...

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
@agrover review? I plan to squash "STASH" commit into "Add dependencies..." commit before merge. However, it contains all the changes.

**Comment by agrover** [comment]
I'm getting a little confused looking at this, can you go ahead and squash that last commit?

**Comment by mulkieran** [comment]
squashed.

**Comment by agrover** [comment]
thanks. 👍

**Pull request merged**
