### PR TITLE
Also catch and process an AttributeError

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #145

### CODE REVIEW

**Comment by agrover** [comment]
> "There seems to be a typo in the source at line %d in file "
                   "%s. The offending line is \"%s\".")

Can this be terser? "Code error at line %d in file %s: \"%s\"."

**Comment by mulkieran** [comment]
These are explanations, so I don't really think we should go for terseness. But typo is too reductionist, so often the problem is that the type is wrong. I've changed the explanation to make it less likely to be wrong.

**Comment by agrover** [comment]
I'd like to omit "most likely" because don't we know there definitely is an error?

I'd like to omit "offending" because it's somewhat folksy.

**Comment by mulkieran** [comment]
We know there is an error, but we are only making an informed guess about the cause of the error. That is why "Most likely".

**Comment by mulkieran** [comment]
"offending" isn't folksy, but it is not necessary either. I can leave it out.

**Comment by agrover** [comment]
ok, I'm done bikeshedding :smiley:

**Pull request merged**
