### PR TITLE
Advance current development environment to Fedora 37

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/project#544

### CODE REVIEW

**Review by mulkieran — CHANGES_REQUESTED** [review]
Please grab "Remove unnecessary lambda..." and put it up in a separate PR so we can merge it now.

**Comment by bgurney-rh** [comment]
Created #933 for the unnecessary lambda removal.

**Comment by bgurney-rh** [comment]
Rebased.

**Review by mulkieran — APPROVED** [review]

**Comment by bgurney-rh** [comment]
Rebased.

**Pull request merged**
