### PR TITLE
Pool and filesystem creation tests support idempotency

### PR DESCRIPTION
**Pull request by waltdisgrace**

### CODE REVIEW

**Comment by bgurney-rh** [comment]
We can probably skip the whitebox test I mentioned above.

I just created PR #360, which will bypass the test failure.

**Comment by jbaublitz** [comment]
@waltdisgrace As I mentioned to @bgurney-rh in #360, name collisions definitely should still fail on from the CLI. If it's not, please let me know as that's a bug in our implementation of the original design. Only the DBus API should be idempotent.

**Comment by bgurney-rh** [comment]
In that case, we seem to have a bug.  After installing stratis from the RPMs generated by the blackbox test build:

```
# stratis pool list
Name  Total Physical Size  Total Physical Used
# stratis pool create spool1 /dev/nvme0n1p1
# stratis pool list
Name    Total Physical Size  Total Physical Used
spool1             8.00 GiB               52 MiB
# stratis pool create spool1 /dev/nvme0n1p1
# stratis pool list
Name    Total Physical Size  Total Physical Used
spool1             8.00 GiB               52 MiB
# stratis pool create spool1 /dev/nvme0n1p1
# stratis pool list
Name    Total Physical Size  Total Physical Used
spool1             8.00 GiB               52 MiB
# stratis pool create spool1 /dev/nvme0n1p1
# stratis pool list
Name    Total Physical Size  Total Physical Used
spool1             8.00 GiB               52 MiB
```

**Comment by mulkieran** [comment]
> In that case, we seem to have a bug. After installing stratis from the RPMs generated by the blackbox test build:
> 
> ```
> # stratis pool list
> Name  Total Physical Size  Total Physical Used
> # stratis pool create spool1 /dev/nvme0n1p1
> # stratis pool list
> Name    Total Physical Size  Total Physical Used
> spool1             8.00 GiB               52 MiB
> # stratis pool create spool1 /dev/nvme0n1p1
> # stratis pool list
> Name    Total Physical Size  Total Physical Used
> spool1             8.00 GiB               52 MiB
> # stratis pool create spool1 /dev/nvme0n1p1
> # stratis pool list
> Name    Total Physical Size  Total Physical Used
> spool1             8.00 GiB               52 MiB
> # stratis pool create spool1 /dev/nvme0n1p1
> # stratis pool list
> Name    Total Physical Size  Total Physical Used
> spool1             8.00 GiB               52 MiB
> ```

@bgurney-rh Once https://github.com/stratis-storage/stratis-cli/pull/358 is merged, can you run the same test again and confirm that we get the result we expect, which should be a helpful error message and a non-zero exit code? If not we do have a bug.

**Comment by mulkieran** [comment]
@waltdisgrace I think these can all be dropped. We'll need to wait another iteration, until the CLI idempotency changes go in, but then I think that none of these changes will be necessary.

**Pull request closed without merging**
