### PR TITLE
Update bash completion

### PR DESCRIPTION
**Pull request by carzacc**
Supercedes #710

### CODE REVIEW

**Comment by mulkieran** [comment]
ok to test

**Comment by mulkieran** [comment]
@carzacc Please rebase one last time, and we'll merge immediately.

**Comment by carzacc** [comment]
> @carzacc Please rebase one last time, and we'll merge immediately.

Is it fine now?

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
Done, thx!

**Pull request merged**
