### PR TITLE
Fix pool destroy and rename

### PR DESCRIPTION
**Pull request by agrover**
A couple spots were left over using old names, and this caused "Bad keys"
errors.

Signed-off-by: Andy Grover <agrover@redhat.com>

### CODE REVIEW

**Comment by agrover** [comment]
@mulkieran why is CI failing here?

**Comment by mulkieran** [comment]
@agrover Looks like pylint got an update since the last time any changes were made to this project.

**Comment by agrover** [comment]
```
src/stratis_cli/_errors.py:68: [R1705(no-else-return), StratisCliValueError.__str__] Unnecessary "else" after "return"
```

I think that code looks fine so I'm going to disable this lint here.

**Comment by agrover** [comment]
With these changes I can use `stratis` to remove and rename the pool, yes -- is that what you were asking?

**Pull request merged**
