### PR TITLE
Issue project 310

### PR DESCRIPTION
**Pull request by mulkieran**
Related https://github.com/stratis-storage/project/issues/310

### CODE REVIEW

**Comment by mulkieran** [comment]
Right now we only have on cause for alerts. May have more in future. Currently, we just display the values of the strings sent over the D-Bus. At some point, we will probably want to use codes, with a programmatically available explanation.

**Comment by jbaublitz** [comment]
> Right now we only have on cause for alerts. May have more in future. Currently, we just display the values of the strings sent over the D-Bus. At some point, we will probably want to use codes, with a programmatically available explanation.

That sounds like a more reasonable solution.

**Review by drckeefe — APPROVED** [review]

**Review by drckeefe — APPROVED** [review]

**Comment by mulkieran** [comment]
stratisd bug is now fixed, see tests https://github.com/stratis-storage/stratis-cli/pull/816/checks?check_run_id=3247840386 for a few examples of a pool listing. Look for "Alerts".

**Comment by mulkieran** [comment]
@jbaublitz Adding you, in case you want to comment on the design.

**Pull request closed without merging**
