### PR TITLE
Increase timeout over default

### PR DESCRIPTION
**Pull request by tasleson**
The stratisd daemon will at times exceed the default timeout of
~25 seconds if we allow it to create more than 1 FS at a time.
At this time we are advocating that the timeout be set to
something much longer to reduce the probability of exceeding
the timeout.

Signed-off-by: Tony Asleson <tasleson@redhat.com>

### CODE REVIEW

**Comment by agrover** [comment]
I'm sure the substance of this is fine, but there seems to be a number of other (automatic?) changes. I'm sure are they are also uncontroversial, but please put them in a separate PR? Thanks.

**Comment by agrover** [comment]
Actually I think the just-merged #161 fixed the same lints, so if this just gets rebased we should be good to go.

**Comment by tasleson** [comment]
@agrover Re-based

**Comment by tasleson** [comment]
Constant moved to `_actions/_constants.py`

**Pull request merged**
