### PR TITLE
Use new version of Manager interface in blackbox tests

### PR DESCRIPTION
**Pull request by jbaublitz**
Resolves the first part of #510

### CODE REVIEW

**Comment by jbaublitz** [comment]
@bgurney-rh Can you test this PR for the blackbox tests? It shouldn't break anything but I just want to be sure.

**Comment by bgurney-rh** [comment]
@jbaublitz yes; I'm starting a test now.

**Comment by bgurney-rh** [comment]
@jbaublitz the test output a number of "More items found in D-Bus signature than in Python arguments" errors; I'll stand by for an update.

**Comment by jbaublitz** [comment]
Rebased.

@mulkieran I have not changed `make_test_pool` yet because we are not going to add encrypted test pools in this PR. I have only made the necessary changes to the D-Bus call wrapper.

@bgurney-rh Once this passes CI, I think it's ready for another test.

**Comment by bgurney-rh** [comment]
@jbaublitz I just finished a blackbox test run with these commits, and it passes.

**Pull request closed without merging**
