### PR TITLE
Bump to using stratisd 3.0.0

### PR DESCRIPTION
**Pull request by mulkieran**
Related https://github.com/stratis-storage/project/issues/316

### CODE REVIEW

**Comment by mulkieran** [comment]
The three bottom tests are expected to fail.

**Comment by mulkieran** [comment]
All tests should now pass

**Comment by mulkieran** [comment]
Draft...temporary commit should be removed in final version.

**Review by jbaublitz — COMMENTED** [review]
This looks good to me!

**Pull request closed without merging**
