### PR TITLE
Add TEST_RUNNER for whitebox tests

### PR DESCRIPTION
**Pull request by bgurney-rh**
Supersedes: #604 
Related: #587

### CODE REVIEW

**Comment by bgurney-rh** [comment]
The Travis build passed; it looks like there's a communication issue between travis-ci and github.

**Comment by mulkieran** [comment]
This looks good to me, but there is a complicated bit of introspection-y code that I'ld like to try out, to augment the newly defined exception class. I'll let you know how it turns out.

**Comment by bgurney-rh** [comment]
As a quick test of what the output looks like, here's an example of a whitebox test run, with a clone of the "test_stratis_version" that intentionally misspells the parameter as "verrrrsion", triggering an error from the stratis command:

```
test_stratis_redundancy (integration.test_stratis.StratisTestCase)
Getting redundancy should just succeed. ... ok
test_stratis_verrrrsion (integration.test_stratis.StratisTestCase)
Getting verrrrsion should fail, and print an exception. ... usage: stratis daemon [-h] {redundancy,version} ...
stratis daemon: error: invalid choice: 'verrrrsion' (choose from 'redundancy', 'version')
ERROR
test_stratis_version (integration.test_stratis.StratisTestCase)
Getting version should just succeed. ... ok

======================================================================
ERROR: test_stratis_verrrrsion (integration.test_stratis.StratisTestCase)
Getting verrrrsion should fail, and print an exception.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.7/argparse.py", line 1996, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib64/python3.7/argparse.py", line 1952, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.7/argparse.py", line 1845, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib64/python3.7/argparse.py", line 2386, in _get_values
    self._check_value(action, value[0])
  File "/usr/lib64/python3.7/argparse.py", line 2433, in _check_value
    raise ArgumentError(action, msg % args)
argparse.ArgumentError: invalid choice: 'verrrrsion' (choose from 'redundancy', 'version')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bgurney-rh/stratis-cli/tests/whitebox/integration/test_stratis.py", line 48, in test_stratis_verrrrsion
    TEST_RUNNER(command_line)
  File "/root/bgurney-rh/stratis-cli/tests/whitebox/integration/_misc.py", line 190, in test_runner
    RUNNER(command_line)
  File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_main.py", line 40, in the_func
    result = parser.parse_args(command_line_args)
  File "/usr/lib64/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.7/argparse.py", line 1996, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib64/python3.7/argparse.py", line 1952, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.7/argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.7/argparse.py", line 1158, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib64/python3.7/argparse.py", line 1794, in parse_known_args
    self.error(str(err))
  File "/usr/lib64/python3.7/argparse.py", line 2508, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib64/python3.7/argparse.py", line 2495, in exit
    _sys.exit(status)
SystemExit: 2
```

**Comment by mulkieran** [comment]
@bgurney-rh: This is a good test, because it shows we _don't_ have all the cases we wanted to covered. Notice how it is still an ```ERROR```, not a ```FAILURE```. Try another test where parsing succeeds but the actual command has some reason to fail. That way we should see the test classified as a failure.

What the above test means is that there is a bit more work to do on ```test_runner```, also, as well as the exception, I think.

**Comment by bgurney-rh** [comment]
I tried adding a "test_add_data_again" variant before the true test would actually execute, with the expectation that it would succeed (while in truth, it will fail):

```
diff --git a/tests/whitebox/integration/pool/test_add.py b/tests/whitebox/integration/pool/test_add.py
index cfc58bb..b4b0a4c 100644
--- a/tests/whitebox/integration/pool/test_add.py
+++ b/tests/whitebox/integration/pool/test_add.py
@@ -92,6 +92,13 @@ class AddDataTestCase1(SimTestCase):
         command_line = self._MENU + [self._POOLNAME] + _DEVICE_STRATEGY()
         TEST_RUNNER(command_line)
 
+    def test_add_data_abnormal(self):
+        """
+        Test that adding new devices again fails, and show exception.
+        """
+        command_line = self._MENU + [self._POOLNAME] + self._DEVICES
+        TEST_RUNNER(command_line)
+
     def test_add_data_again(self):
         """
         Test that trying to add the same devices twice results in an
```

```
test_add_data (integration.pool.test_add.AddDataTestCase1)
Test that adding new devices to data tier succeeds. ... ok
test_add_data_abnormal (integration.pool.test_add.AddDataTestCase1)
Test that adding new devices again fails, and show exception. ... FAIL
test_add_data_again (integration.pool.test_add.AddDataTestCase1)
Test that trying to add the same devices twice results in an ... Execution failed:
It appears that you issued an unintended command: The 'add to data' action has no effect for resource /dev/7KQP 

ok

...

======================================================================
FAIL: test_add_data_abnormal (integration.pool.test_add.AddDataTestCase1)
Test that adding new devices again fails, and show exception.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_main.py", line 43, in the_func
    result.func(result)
  File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_parser/_parser.py", line 87, in wrapped_func
    func(*args)
  File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_actions/_top.py", line 540, in add_data_devices
    namespace.pool_name, managed_objects, blockdevs, BlockDevTiers.Data
  File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_actions/_top.py", line 140, in _check_same_tier
    to_be_added.intersection(owned_by_current_pool),
stratis_cli._errors.StratisCliPartialChangeError: The 'add to data' action has no effect for resource /dev/7KQP

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/bgurney-rh/stratis-cli/tests/whitebox/integration/_misc.py", line 190, in test_runner
    RUNNER(command_line)
  File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_main.py", line 60, in the_func
    raise StratisCliActionError(command_line_args, result) from err
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['--propagate', 'pool', 'add-data', 'deadpool', '/dev/7KQP'] which were parsed to Namespace(blockdevs=['/dev/7KQP'], func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7f0bdeb1f320>, pool_name='deadpool', propagate=True) failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/bgurney-rh/stratis-cli/tests/whitebox/integration/pool/test_add.py", line 100, in test_add_data_abnormal
    TEST_RUNNER(command_line)
  File "/root/bgurney-rh/stratis-cli/tests/whitebox/integration/_misc.py", line 192, in test_runner
    raise StratisCliTestRunError from err
integration._misc.StratisCliTestRunError

----------------------------------------------------------------------
Ran 88 tests in 83.637s

FAILED (failures=1)
make: *** [Makefile:51: dbus-tests] Error 1
```

**Comment by mulkieran** [comment]
> I tried adding a "test_add_data_again" variant before the true test would actually execute, with the expectation that it would succeed (while in truth, it will fail):
> 
> ```
> diff --git a/tests/whitebox/integration/pool/test_add.py b/tests/whitebox/integration/pool/test_add.py
> index cfc58bb..b4b0a4c 100644
> --- a/tests/whitebox/integration/pool/test_add.py
> +++ b/tests/whitebox/integration/pool/test_add.py
> @@ -92,6 +92,13 @@ class AddDataTestCase1(SimTestCase):
>          command_line = self._MENU + [self._POOLNAME] + _DEVICE_STRATEGY()
>          TEST_RUNNER(command_line)
>  
> +    def test_add_data_abnormal(self):
> +        """
> +        Test that adding new devices again fails, and show exception.
> +        """
> +        command_line = self._MENU + [self._POOLNAME] + self._DEVICES
> +        TEST_RUNNER(command_line)
> +
>      def test_add_data_again(self):
>          """
>          Test that trying to add the same devices twice results in an
> ```
> 
> ```
> test_add_data (integration.pool.test_add.AddDataTestCase1)
> Test that adding new devices to data tier succeeds. ... ok
> test_add_data_abnormal (integration.pool.test_add.AddDataTestCase1)
> Test that adding new devices again fails, and show exception. ... FAIL
> test_add_data_again (integration.pool.test_add.AddDataTestCase1)
> Test that trying to add the same devices twice results in an ... Execution failed:
> It appears that you issued an unintended command: The 'add to data' action has no effect for resource /dev/7KQP 
> 
> ok
> 
> ...
> 
> ======================================================================
> FAIL: test_add_data_abnormal (integration.pool.test_add.AddDataTestCase1)
> Test that adding new devices again fails, and show exception.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_main.py", line 43, in the_func
>     result.func(result)
>   File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_parser/_parser.py", line 87, in wrapped_func
>     func(*args)
>   File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_actions/_top.py", line 540, in add_data_devices
>     namespace.pool_name, managed_objects, blockdevs, BlockDevTiers.Data
>   File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_actions/_top.py", line 140, in _check_same_tier
>     to_be_added.intersection(owned_by_current_pool),
> stratis_cli._errors.StratisCliPartialChangeError: The 'add to data' action has no effect for resource /dev/7KQP
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/root/bgurney-rh/stratis-cli/tests/whitebox/integration/_misc.py", line 190, in test_runner
>     RUNNER(command_line)
>   File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_main.py", line 60, in the_func
>     raise StratisCliActionError(command_line_args, result) from err
> stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['--propagate', 'pool', 'add-data', 'deadpool', '/dev/7KQP'] which were parsed to Namespace(blockdevs=['/dev/7KQP'], func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7f0bdeb1f320>, pool_name='deadpool', propagate=True) failed
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/root/bgurney-rh/stratis-cli/tests/whitebox/integration/pool/test_add.py", line 100, in test_add_data_abnormal
>     TEST_RUNNER(command_line)
>   File "/root/bgurney-rh/stratis-cli/tests/whitebox/integration/_misc.py", line 192, in test_runner
>     raise StratisCliTestRunError from err
> integration._misc.StratisCliTestRunError
> 
> ----------------------------------------------------------------------
> Ran 88 tests in 83.637s
> 
> FAILED (failures=1)
> make: *** [Makefile:51: dbus-tests] Error 1
> ```

This is behaving exactly as we want here...but we might want a more helpful error message emitted in connection with the newly defined error.

**Comment by mulkieran** [comment]
Actually, I think it makes sense to accept a parsing problem as a test ERROR, not a FAILURE, as we never have any reason to test the parser in these tests, and where we test the parse we always look for failures. So, that simplifies things.

**Comment by mulkieran** [comment]
Ok. So that means there's only one thing left to do. Define an ```__str__``` method for ```StratisCliTestRunError``` and have it say something like: ```Unexpected failure of command-line call in test." or something like that. I don't think we need anything more, since we run with ```--propagate``` set and that shows us the entire exception chain anyway.

**Comment by mulkieran** [comment]
@bgurney-rh I think this is fine. Can you run off a test to show what the stack trace looks like with the newly introduced exception message?

**Comment by bgurney-rh** [comment]
Here's the new output:
```
======================================================================
FAIL: test_add_data_abnormal (integration.pool.test_add.AddDataTestCase1)
Test that adding new devices again fails, and show exception.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_main.py", line 43, in the_func
    result.func(result)
  File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_parser/_parser.py", line 87, in wrapped_func
    func(*args)
  File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_actions/_top.py", line 540, in add_data_devices
    namespace.pool_name, managed_objects, blockdevs, BlockDevTiers.Data
  File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_actions/_top.py", line 140, in _check_same_tier
    to_be_added.intersection(owned_by_current_pool),
stratis_cli._errors.StratisCliPartialChangeError: The 'add to data' action has no effect for resource /dev/U3IV

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/bgurney-rh/stratis-cli/tests/whitebox/integration/_misc.py", line 193, in test_runner
    RUNNER(command_line)
  File "/root/bgurney-rh/stratis-cli/src/stratis_cli/_main.py", line 60, in the_func
    raise StratisCliActionError(command_line_args, result) from err
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['--propagate', 'pool', 'add-data', 'deadpool', '/dev/U3IV'] which were parsed to Namespace(blockdevs=['/dev/U3IV'], func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7f46e73163b0>, pool_name='deadpool', propagate=True) failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/bgurney-rh/stratis-cli/tests/whitebox/integration/pool/test_add.py", line 100, in test_add_data_abnormal
    TEST_RUNNER(command_line)
  File "/root/bgurney-rh/stratis-cli/tests/whitebox/integration/_misc.py", line 195, in test_runner
    raise StratisCliTestRunError from err
integration._misc.StratisCliTestRunError: Unexpected failure of command-line call in test
```

**Pull request closed without merging**
