### PR TITLE
Remove terminal handling from stratis-cli

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes stratis-storage/project#209
Blocked by stratis-storage/stratisd#2163

### CODE REVIEW

**Comment by jbaublitz** [comment]
Rebased.

**Comment by jbaublitz** [comment]
@mulkieran Oh! I can add terminal handling to the sim_engine side too, but I think this PR should probably remain unchanged.

**Comment by mulkieran** [comment]
@jbaublitz Yeah, we'ld better make the sim engine behave the same. 

There's a remaining minor but annoying consideration...what if stratisd is responding slowly to D-Bus requests? In that case, the user gets a chance to start typing _before_ the daemon has set the properties of stdin correctly. A possible way to make this happen might be to start a longer running filesystem operation in one window, and then quick in a hurry attempt to set the key in another window. I haven't tried, but it might work. Let's talk about this briefly in standup.

**Comment by jbaublitz** [comment]
@mulkieran I'll try to take a look at the sim engine today! I agree that we should discuss this, but I think this will eventually cease to be a problem with multithreading just like with some of our other D-Bus issues.

**Comment by jbaublitz** [comment]
Rebased.

**Comment by mulkieran** [comment]
@jbaublitz: I think we should bump the required stratisd version in this PR as well.

**Comment by jbaublitz** [comment]
@mulkieran Yes, that makes a lot of sense. I was wondering about that myself. I'll add that to the PR.

**Comment by jbaublitz** [comment]
@mulkieran Ready for review again.

**Review by mulkieran — CHANGES_REQUESTED** [review]
Ok! Please close this and open a final PR. Please keep the version bump in a separate commit.

**Pull request closed without merging**
