### PR TITLE
Handle an exception chain connected with a GetManagedObjects() failure

### PR DESCRIPTION
**Pull request by mulkieran**
Related: https://github.com/stratis-storage/stratisd/pull/2404

### CODE REVIEW

**Comment by mulkieran** [comment]
@bgurney-rh Can you test this using the scripts you were running yesterday? We agree that the errors the CLI was encountering were Ok. What we don't like is the stack traces, since we've defined any stack trace appearing under normal operation as a bug in the CLI. So, in lieu of the stack trace, we want to see the error message added in this commit.

**Review by jbaublitz — APPROVED** [review]

**Comment by mulkieran** [comment]
ok, testing works out.

**Comment by mulkieran** [comment]
Looks like this:

```
> stratis pool list
Execution failed:
A D-Bus method failed during execution of the selected command. Most likely, the failure was due to a transient inconsistency in the D-Bus interface and the command will succeed if run again. 
```

instead of the previous stack trace.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
we can ignore the prior, bogus test failure, probably network related.

**Review by drckeefe — APPROVED** [review]

**Pull request merged**
