### PR TITLE
Future-proof Python code

### PR DESCRIPTION
**Pull request by jbaublitz**
Related to stratis-storage/stratisd#1989.

### CODE REVIEW

**Comment by jbaublitz** [comment]
@mulkieran I'm a little confused at the return of the non-top level import linting errors. Do you know why this is?

**Comment by mulkieran** [comment]
Likely when we were running under tox we were running an older version of Python but actually a newer version of pylint. When we switched to what we are running now, we caught some actual errors, presumably because the newer version of Python and the older version of pylint had some better interaction, so it looked like an upgrade all around, but it wasn't actually.

**Comment by jbaublitz** [comment]
@mulkieran I tracked down the Github issue where they added the import check that is breaking CI. This means that this PR will only be relevant when we decide to update pylint in CI.

**Comment by jbaublitz** [comment]
@mulkieran @bgurney-rh While I can update this easily in Travis, how would you like me to proceed for Jenkins? I don't think we can't put this through until we update the Jenkins worker nodes, but I'm not sure if there's another way to handle that.

**Comment by mulkieran** [comment]
@jbaublitz: We can't put this through until @lleshchi  and I are ready to move up a Fedora version. I don't think it'll matter to the Jenkins nodes, but I expect that @bgurney-rh will be in process of updating those soon or is already.

**Comment by mulkieran** [comment]
An alternative is to do a dynamic check for the pylint version that is being run against, and then we can work with both pylint versions. I'm going to give that a go, especially as recent changes have made this PR pretty stale.

**Comment by mulkieran** [comment]
> An alternative is to do a dynamic check for the pylint version that is being run against, and then we can work with both pylint versions. I'm going to give that a go, especially as recent changes have made this PR pretty stale.

Alas, it's not just pylint, it's also black that causes the problem, since the new version formats one line differently. So, we'll just have to halt for a bit longer.

**Comment by jbaublitz** [comment]
Out of date. Closing and waiting until we migrate to Fedora 31.

**Pull request closed without merging**
