### PR TITLE
Update Bash completion

### PR DESCRIPTION
**Pull request by carzacc**
I wrote the bash completion script a few years ago at this point and many months have passed since I last updated it.

This is another update to reflect the changes to the CLI since the last time I updated it, I tested the big changes and will test the script some more tomorrow, meanwhile you can judge the code and inform me of any changes you want to be made.

### CODE REVIEW

**Comment by carzacc** [comment]
Actually, there's one thing I need to fix: passing --redundancy to pool create will make the script skip the pool name and try to complete block device names, I'll fix that asap

**Comment by carzacc** [comment]
> Actually, there's one thing I need to fix: passing --redundancy to pool create will make the script skip the pool name and try to complete block device names, I'll fix that asap

Fixed and rebased.

**Comment by poizen18** [comment]
@carzacc 
I reviewed the source code, there is just one minor change that I would suggest, i.e. adding `list` to the key_subcommands.
Currently it only has the following:
~~~
        key_subcommands="set unset reset"
~~~

That is because `list` is one of the possible values that should be presented to end user.

~~~
# stratis key --help
usage: stratis key [-h] {set,reset,unset,list} ...
~~~

Rest of the source looks good to me. No further changes to be made. Good bash completion indeed :+1:

**Comment by mulkieran** [comment]
@poizen18 Thanks for looking!

**Comment by carzacc** [comment]
@poizen18 fixed and rebased.

**Review by drckeefe — APPROVED** [review]

**Review by poizen18 — APPROVED** [review]
Reviewed!

**Comment by mulkieran** [comment]
@carzacc Please rebase when you get the chance, thx!

**Comment by carzacc** [comment]
@mulkieran Done!

**Comment by mulkieran** [comment]
Jenkins, test this please.

**Comment by mulkieran** [comment]
ok to test

**Pull request merged**
