### PR TITLE
Jbaublitz issue project 192

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
We should expect the Jenkins failures, because the interfaces of certain much used methods have changed.

**Comment by mulkieran** [comment]
AFAICT, ```unlock``` is now all taken care of with addition of ```unlock_method```.

**Comment by mulkieran** [comment]
```unbind``` action checks out and is mostly tested.

**Review by jbaublitz — APPROVED** [review]

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
expected Jenkins failures.

**Review by drckeefe — APPROVED** [review]

**Review by jbaublitz — APPROVED** [review]

**Comment by mulkieran** [comment]
Superceded

**Pull request closed without merging**
