### PR TITLE
Issue project 299

### PR DESCRIPTION
**Pull request by mulkieran**
Related https://github.com/stratis-storage/project/issues/299

### CODE REVIEW

**Comment by mulkieran** [comment]
coverage failure is unsurprising.

**Comment by mulkieran** [comment]
coverage is expected to fail since there are no new tests for the new argument processing yet.

**Comment by mulkieran** [comment]
Completely reworked

**Comment by mulkieran** [comment]
coverage failure is no surprise, no additional tests

**Comment by mulkieran** [comment]
on this side, the only thing left to do is to decide the format used to specify the size.

**Comment by mulkieran** [comment]
Some tests, "Excuection failed" means that the command-line parser was happy w/ the format and sent the command to stratisd. Anything else is a parser failure. All failures to parse a size specification should always receive the same message. This is mostly
due to an implementation detail, w/out the space the size specification is best parsed using a regular expression, which doesn't give an indication of why it failed to match.

```
$ PYTHONPATH=./src ./bin/stratis fs create pn fn --size=64GiB
Execution failed:
It appears that there is no stratisd process running. 

$ PYTHONPATH=./src ./bin/stratis fs create pn fn --size 64GiB
Execution failed:
It appears that there is no stratisd process running. 

$ PYTHONPATH=./src ./bin/stratis fs create pn fn --size 64.5GiB
usage: stratis filesystem create [-h] [--size SIZE]
                                 pool_name fs_name [fs_name ...]
stratis filesystem create: error: argument --size: Ill-formed size specification: Size must be speified using the format <magnitude><units> where <magnitude> is a decimal integer value and <units> is any binary unit specifier in the set "B", "KiB", "MiB", "GiB", "TiB", and "PiB".

$ PYTHONPATH=./src ./bin/stratis fs create pn fn --size 64PiB
Execution failed:
It appears that there is no stratisd process running. 

$ PYTHONPATH=./src ./bin/stratis fs create pn fn --size 64B
Execution failed:
It appears that there is no stratisd process running. 
```

**Review by drckeefe — APPROVED** [review]

**Review by bgurney-rh — APPROVED** [review]

**Review by jbaublitz — APPROVED** [review]

**Pull request closed without merging**
