### PR TITLE
Blame selinux for Disconnected D-Bus error

### PR DESCRIPTION
**Pull request by mulkieran**
Closes https://github.com/stratis-storage/project/issues/233
Supercedes #669

### CODE REVIEW

**Comment by mulkieran** [comment]
@drckeefe Can you test this change?

**Review by drckeefe — APPROVED** [review]

**Comment by drckeefe** [comment]
@mulkieran tested change.  The message is displayed when the connection is dropped.

**Comment by mulkieran** [comment]
We also know that w/ a pseudo terminal the problem is not observed at all. I'm wiling to stick w/ this approach.

**Comment by mulkieran** [comment]
rebased.

**Review by jbaublitz — APPROVED** [review]

**Pull request merged**
