### PR TITLE
Convert no-op engine results into failures

### PR DESCRIPTION
**Pull request by jbaublitz**
Supersedes #321 
Closes stratis-storage/project#51

Leverage stratisd changes to determine when actions have had an effect and fail on no effect.

### CODE REVIEW

**Comment by mulkieran** [comment]
Looks like there are a few test fixes needed after all.

**Comment by jbaublitz** [comment]
I'll clean these up.

**Comment by jbaublitz** [comment]
I've fixed the tests. Please review the most recent commit and once I get approval, I'll squash this and we can merge.

**Comment by jbaublitz** [comment]
Rebased.

**Comment by bgurney-rh** [comment]
I "scouted ahead" on the blackbox test results, by checking out this branch for the stratisd component, and I saw this blackbox test failure:
```
======================================================================
FAIL: test_filesystem_rename_same_name (__main__.StratisCertify)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "stratis-cli-77.77.77/tests/blackbox/stratis_cli_cert.py", line 256, in test_filesystem_rename_same_name
    True,
  File "stratis-cli-77.77.77/tests/blackbox/stratis_cli_cert.py", line 94, in unittest_command
    self.assertEqual(exit_code, exp_exit_code)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 18 tests in 41.607s

FAILED (failures=1)
```

Trying by hand:
```
# stratis pool rename spool1 spool1
Execution failed:
You issued a command that would have had no effect: The 'rename' action has no effect for resource spool1
# echo $?
1
```

**Comment by jbaublitz** [comment]
@bgurney-rh This is the correct behavior. We want actions like creating two devices with the same name or renaming something to itself to fail as it performs no action in the engine.

**Comment by bgurney-rh** [comment]
OK; I tried changing that test to verify that the command fails, and all of the blackbox tests pass.

Created PR #361 for the blackbox test modification to test_filesystem_rename_same_name.

**Pull request merged**
