### PR TITLE
Add report command

### LINKED ISSUE #543: Add a command to use the Reports interface
* Make the output human not machine readable; we imagine there's a library to help us here.
* We might want a separate subcommand, though, as it does not properly belong to ```daemon``` and certainly not to the other subcommands. We could call it ```report``` and that would be clear enough.

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #543

### CODE REVIEW

**Comment by mulkieran** [comment]
Re-running one errored Travis task;

**Comment by jbaublitz** [comment]
We should not merge this quite yet. I tested it against the new report I'm working on for full engine state and I need to tweak the formatting a bit so it looks more readable.

**Comment by jbaublitz** [comment]
@mulkieran Does this output format work for you?

```
{
    "errored_pools": [],
    "pools": [
        {
            "blockdevs": {
                "cachedevs": [],
                "datadevs": [
                    {
                        "path": "/dev/sdb3",
                        "uuid": "97e71f9acda24d4ea82b74bbde91730d"
                    },
                    {
                        "path": "/dev/sdb2",
                        "uuid": "276a9c4f4ebb41ecb3e5e1f327256620"
                    },
                    {
                        "path": "/dev/sdb1",
                        "uuid": "d9ff80a16c3d47bcb481091e88ed2091"
                    }
                ]
            },
            "filesystems": [
                {
                    "name": "test-fs",
                    "uuid": "722b3afb635541b6a51d1929bedbba96"
                }
            ],
            "name": "test",
            "uuid": "4717c665001047e8b3730d07f0bb6098"
        }
    ]
}
``` 

This looks much better to me than what it was before and I'll push the changes if this looks good to you.

**Comment by mulkieran** [comment]
@jbaublitz: The displayed formatting is fine with me.

**Comment by jbaublitz** [comment]
Changes applied. This is ready for final review.

**Pull request closed without merging**
