### PR TITLE
Add fish completion: This is a dirty hack implementation, but it works

### PR DESCRIPTION
**Pull request by axionl**

### CODE REVIEW

**Comment by agrover** [comment]
Hi, thanks for the PR!

Having someone who knows Fish (you) maintain this is great, much thanks. Do you want this to be merged straight away, or should we be waiting for a cleaner version?

**Comment by axionl** [comment]
> Hi, thanks for the PR!
> 
> Having someone who knows Fish (you) maintain this is great, much thanks. Do you want this to be merged straight away, or should we be waiting for a cleaner version?

I'm just a fish shell user for a long time but using `stratis-storage` in a short time. For some reason, there is no so much user of `stratis-storage`, but this package was officially supported by archlinux. I hope this package will get more support and other people can help me to improve it, because I have no idea of some features supported for the time being. If something goes wrong, I will try my best to solve it.

Merge it is ok if there was no other problem and you can test it in the easily way, just download the `fish-shell` by your package manager, and sourece the completion file by fish.

**Comment by mulkieran** [comment]
fish seems fun to me, but fish scripting is not my thing, so I'm abstaining from review.

**Comment by tasleson** [comment]
Completions appear to go in `/usr/share/fish/completions`

**Comment by trgill** [comment]
ok to test

**Comment by tasleson** [comment]
BZ filed to get vendor completions directory created: https://bugzilla.redhat.com/show_bug.cgi?id=1683398

**Pull request merged**
