### PR TITLE
Add support for rebinding

### LINKED ISSUE #776: Add support for rebinding in stratis-cli
References https://github.com/stratis-storage/stratisd/issues/2358/

### PR DESCRIPTION
**Pull request by mulkieran**
Closes #776

### CODE REVIEW

**Comment by mulkieran** [comment]
@drckeefe Please take a look at this. It's complete, but still in Draft so that I do not accidentally merge the temporary commit which targets the tests to the corresponding stratisd PR.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Tests are failing because rebase and fixing of conflicts for https://github.com/stratis-storage/stratisd/pull/2633 is now necessary. Test failures can be ignored.

**Comment by mulkieran** [comment]
rebased. I'm expecting the tests to pass now.

**Review by jbaublitz — APPROVED** [review]
This looks good to me so far!

**Review by drckeefe — APPROVED** [review]

**Comment by mulkieran** [comment]
Re-running against current PR.

**Comment by mulkieran** [comment]
Tests all passed again.

**Comment by mulkieran** [comment]
Superceded by #805

**Pull request closed without merging**
