### PR TITLE
Catch KeyboardInterrupt at the outermost level

### PR DESCRIPTION
**Pull request by mulkieran**
Closes: #250.

### CODE REVIEW

**Comment by mulkieran** [comment]
This derives from a bz. Since it is, AFAICT, so straightforward to satisfy, I think it might as well be taken care of now.

**Comment by mulkieran** [comment]
> In the BZ https://bugzilla.redhat.com/show_bug.cgi?id=1686652#c1 you mention returning an exit code of 130. This change results in an exit of 1 with the message going to stderr. I'm thinking that it would be good for someone scripting the command line to know if it got interrupted by a signal with the command line returning a unique code. This would allow the caller to know that the request will likely complete as requested at some point in the future.

It is easy enough to return an exit code of 130.

I chose to go w/ 1, because it is correct, if not very precise.

I think it makes sense to move this ahead as is, and file an issue about working out status codes. It's one of those things that is surprisingly lacking in standards and apparently some user would object to any status code value above 127.

**Comment by tasleson** [comment]
Follow-up issue https://github.com/stratis-storage/stratis-cli/issues/251

**Comment by mulkieran** [comment]
Superceded by #254.

**Pull request closed without merging**
