### PR TITLE
Correct explanation of --propagate flag in man page

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by agrover** [comment]
I think this means to say that when debugging the daemon it's useful to use --propagate, but it seems to say that everyone including non-developer users should use it always, which I don't think is true.

**Comment by mulkieran** [comment]
The Recommendation part is under sub-heading ```REPORTING BUGS AND DEVELOPMENT``` to restrict the "run with --propagate" advice to that context. I guess it could be restricted further, somehow.

**Comment by mulkieran** [comment]
Ok. I'm putting just the non-controversial bit up for review at this time.

**Comment by agrover** [comment]
> Allow any exceptions raised during execution to propagate.

I don't think this is quite accessible enough to non-programmers. The words that are tripping me up are "exceptions" -- can we say "errors"? -- and "propagate". I'm assuming the user is reading this because they don't know what propagate means in this context, so best to use other word choices in the explanation.

**Comment by mulkieran** [comment]
I think saying what the effect of the flag actually is is necessary. I added a bit to make it sound like a "developer" kind of thing, not for typical users.

**Comment by agrover** [comment]
I'm saying I, as a developer, still don't know what "Allow any exceptions raised during execution to propagate" means. Looking at the code it appears to just mean printing the exception/stacktrace instead of just printing the error. If so why is "--propagate" a better description than something like "--verbose-errors"?

**Comment by mulkieran** [comment]
It means allow the exception to propagate; leave it to the interpreter to decide what to do when it catches the exception.

**Comment by mulkieran** [comment]
@agrover review?

**Comment by mulkieran** [comment]
Are you telling me that it is not the intepreter that prints the exception, but the shell?

**Comment by mulkieran** [comment]
New commit message, line, and ordering.

@agrover review, please?

**Comment by agrover** [comment]
love it. merging.

**Pull request merged**
