### PR TITLE
Add isort to Makefile and apply make fmt

### PR DESCRIPTION
**Pull request by jbaublitz**
Supersedes #329 
Related stratis-storage/project#40

### CODE REVIEW

**Comment by jbaublitz** [comment]
For now, just rebasing onto develop and seeing if CI passes.

**Comment by mulkieran** [comment]
We can move this up to November. There are some groupings that I don't like, so I'ld like to tinker w/ it before it goes in. OTOH, it's automatic, so if we can accept somethings that we slightly don't like, it'll be the better choice.

**Comment by mulkieran** [comment]
Note that if we choose to do this for stratis-cli, we'll want to do this for all the other Python projects as well.

**Comment by jbaublitz** [comment]
I am slightly confused by some of the reordering. I've been looking at it a bit more to try to figure out exactly how they're being grouped.

**Comment by mulkieran** [comment]
I'm going to test these changes out in one of the smaller libraries, just to get a feel for how it works.

**Comment by mulkieran** [comment]
We can take our time on this, moving to December.

**Comment by jbaublitz** [comment]
Superseded by #422

**Pull request closed without merging**
