### PR TITLE
Try to make CLI errors a bit more interpretable

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #70
Resolves: #83

### CODE REVIEW

**Comment by mulkieran** [comment]
Simple example:

```
[mulhern@localhost stratis-cli]$ PYTHONPATH=./src ./bin/stratis pool list
Execution failed; causes in order of specificity:
Error 0: The name org.storage.stratis1 was not provided by any .service files
```

**Comment by mulkieran** [comment]
Old style:

```
[mulhern@localhost stratis-cli]$ PYTHONPATH=./src ./bin/stratis pool create test1 bd
Execution failed: 
```
it caught a DPClientRuntimeError which has str representation "" and just printed that.

New way:

```
[mulhern@localhost stratis-cli]$ PYTHONPATH=./src ./bin/stratis pool create test1 bd
Execution failed; causes in order of specificity:
Error 0: Invalid argument 0
```

Traversed the cause chain, printing out string representation of errors that have one.

The error is artificially generated. I changed the data so that stratis-cli exported a boolean for the value of the pool name, so the error string is correct.

**Comment by agrover** [comment]
I like it. Slight bikeshed -- replace "causes in order of specificity" with "caused by"?

**Comment by mulkieran** [comment]
Ok. String is now "Execution failure caused by:"

**Comment by mulkieran** [comment]
Here is another induced error, two item chain:

```
[mulhern@localhost stratis-cli]$ PYTHONPATH=./src ./bin/stratis pool create test1 bd
Execution failure caused by:
Error 0: value 'test1' for parameter expr is unacceptable: could not be transformed
Error 1: invalid literal for int() with base 10: 'test1'
```

The induced error was that the name of the pool should be transformable to an int. So we get the actual exception from ```int(test1)``` as Error 1, and then the exception from the ```into-dbus-python``` library method as Error 0.

**Comment by mulkieran** [comment]
Ok. I think this is ready to go.

**Comment by agrover** [comment]
Just to confirm my understanding here, if we `raise` because --propagate was given, if we have three chained exceptions we'll see the (messy but useful to devs) three separate stack traces, right?

On another topic, I found myself getting hung up on the "Execution failed but no printable cause" string. Is this really needed? When do we see str(error) fail? If never, do we need this? If sometimes, is using `error.__name__` as a fallback enough to guarantee we always have something, and thus can avoid this scenario?

Finally, I'm worried looking at the example given that it's not clear that Error 1 caused Error 0, and not vice versa, if users misinterpret the ordering. Users may also miss the causal relationship between the two, and think that the command generated two separate errors instead of one linked error. Given this, I would recommend reversing the order so highest-level exception is given last (would users tend to look at the last thing first?), and inserted "caused" (or "caused by" if you decide to stick with the existing ordering) between lines to help the user understand the ordering better from context.

Finally finally (hey, I think this stuff is really important), It might be nice to number errors starting with 1 instead of 0.

**Comment by mulkieran** [comment]
> Just to confirm my understanding here, if we raise because --propagate was given, if we have three chained exceptions we'll see the (messy but useful to devs) three separate stack traces, right?

Correct.

**Comment by mulkieran** [comment]
> On another topic, I found myself getting hung up on the "Execution failed but no printable cause" string. Is this really needed? When do we see str(error) fail? If never, do we need this? If sometimes, is using error.__name__ as a fallback enough to guarantee we always have something, and thus can avoid this scenario?

It is unlikely that we'll ever have an empty string for the error with these changes, but who knows with Python? How about just propagating the exception when that happens? That should make it more likely that it will be reported as a bug, and if reported, that we can fix it.

**Comment by agrover** [comment]
Sounds good to me.

**Comment by mulkieran** [comment]
Here is an unnumbered approach:

```
[mulhern@localhost stratis-cli]$ PYTHONPATH=./src ./bin/stratis pool create test1 junk
Execution failure caused by:
invalid literal for int() with base 10: 'test1'
    which in turn caused
value 'test1' for parameter expr is unacceptable: could not be transformed
```

**Comment by mulkieran** [comment]
With enhanced dbus-python-client-gen messages:

```
[mulhern@localhost stratis-cli]$ PYTHONPATH=./src ./bin/stratis  pool create 1 junk
Execution failure caused by:
Invalid argument 0
    which in turn caused
Error while invoking method "CreatePool" belonging to interface "org.storage.stratis1.Manager" with arguments (1, dbus.Struct((dbus.Boolean(True), dbus.UInt16(0)), signature=dbus.Signature('bq')), 0, dbus.Array([dbus.String('junk')], signature=dbus.Signature('s')))
```

**Comment by mulkieran** [comment]
Another dbus-python-client-gen "enhanced" version:

```
[mulhern@localhost stratis-cli]$ PYTHONPATH=./src ./bin/stratis pool create test junk
Execution failure caused by:
invalid literal for int() with base 10: 'test'
    which in turn caused
value 'test' for parameter expr is unacceptable: could not be transformed
    which in turn caused
Failed to format arguments (test, (True, 0), False, ['junk'])
```

**Comment by agrover** [comment]
seems like an improvement to me!

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Commits squashed, code unchanged.

**Comment by mulkieran** [comment]
Might as well try the ActionError idea in #70.

**Comment by mulkieran** [comment]
With our one interpretation string:

```
[mulhern@localhost stratis-cli]$ PYTHONPATH=./src ./bin/stratis daemon version
Execution failure caused by:
Could not get owner of name 'org.storage.stratis1': no such name
    which in turn caused
The name org.storage.stratis1 was not provided by any .service files

Most likely the Stratis daemon, stratisd, is not running.
```

**Comment by agrover** [comment]
looks very good. nit: Please put a ':' after "which in turn caused"? Thanks! :+1:

**Comment by mulkieran** [comment]
Ok. ':' added, moved to review final.

**Pull request merged**
