### PR TITLE
Print out some information about the pools

### PR DESCRIPTION
**Pull request by mulkieran**
Use a generic table printer to do it.
The generic table printer is obviously incomplete, but can be improved as
necessary later.

Resolves: #63

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
This became suddenly a lot easier after #68 got merged.

**Comment by mulkieran** [comment]
@agrover review?

**Comment by mulkieran** [comment]
Pools are preposterously large in the sim engine, output looks like this:

```
[mulhern@localhost stratis-cli]$ PYTHONPATH=./src ./bin/stratis pool list
Name        Total Physical Size (sectors)  Total Physical Used (sectors)
deadpool              1152921504606846976                              0
```

**Comment by mulkieran** [comment]
Whoops! Keys might as well be integers, less danger of misspellings causing irritating bugs.

**Comment by mulkieran** [comment]
@agrover , should be ready now.

**Comment by mulkieran** [comment]
@agrover review? Jenkins test failure is meaningless, currently.

**Comment by agrover** [comment]
looks good 👍

**Pull request merged**
